name: VMware Event Router Development Build

# triggered on every push to development but only when changes inside
# vmware-event-router (sub)dir(s)
on:
  push:
    paths:
      - 'vmware-event-router/**'
    branches:
      - "development"

# run all jobs with these defaults, unless specified otherwise
defaults:
  run:
    shell: bash
    working-directory: ./vmware-event-router

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source (this.release branch)
        uses: actions/checkout@v2
      - name: get the short commit ID
        id: get_short_commit
        run: echo ::set-output name=COMMIT::$(echo $GITHUB_SHA | cut -c -8)
      - name: log in to Docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
        run: echo "${DOCKER_SECRET}" | docker login -u "${DOCKER_USER}" --password-stdin
      - name: test and build pre-release image
        env: 
          COMMIT: ${{ steps.get_short_commit.outputs.COMMIT }}        
        run: |
          echo "Building pre-release of vmware-event-router with commit $COMMIT"        
          make
          docker tag vmware/veba-event-router:latest vmware/veba-event-router:$COMMIT
      - name: push just the pre-release image
        env: 
          COMMIT: ${{ steps.get_short_commit.outputs.COMMIT }}        
        run: |
          docker push vmware/veba-event-router:$COMMIT
